[package]
name = "rzm"
version = "0.1.0"
authors = ["George Madrid <gmadrid@gmail.com>"]

[dependencies]
byteorder = "0.5.3"
clap = "2.13"
log = "0.3.6"
ncurses = "5.84.0"
rand = "0.3"

[[bin]]
name = "rzm"
doc = false
